services:
  # WireMock - Salesforce Mock
  salesforce-mock:
    image: wiremock/wiremock:3.3.1
    container_name: salesforce-mock
    ports:
      - "8081:8080"
    volumes:
      - ./mocks/salesforce:/home/wiremock
    command: --verbose --global-response-templating
    networks:
      - motor-network

  # WireMock - Genesys Mock
  genesys-mock:
    image: wiremock/wiremock:3.3.1
    container_name: genesys-mock
    ports:
      - "8082:8080"
    volumes:
      - ./mocks/genesys:/home/wiremock
    command: --verbose --global-response-templating
    networks:
      - motor-network

networks:
  motor-network:
    driver: bridge
